version: "3.8"
services:
    db:
        image: mysql
        container_name: user-rest-api_db
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - user-rest-api

    phpmyadmin:
        image: phpmyadmin
        container_name: user-rest-api_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - user-rest-api

    www:
        build: docker/php
        container_name: user-rest-api_backend
        ports:
          - "8741:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - user-rest-api

networks:
    user-rest-api:

volumes:
    db-data: